// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Intrinsic dimensions and encoded widths for every photo in public/img/.
// `w`/`h` are the source pixel size, used to set the aspect ratio up front so
// images reserve layout space before they load. `bg` is the dominant colour,
// painted behind the image while it decodes.

export type ImageMeta = {
  /** Intrinsic width of the source file, in px. */
  w: number;
  /** Intrinsic height of the source file, in px. */
  h: number;
  /** Dominant colour, as a hex string. */
  bg: string;
  /** Widths actually encoded for this image. */
  widths: number[];
};

export const images = {
  "agent-client-handshake": {
    "w": 1880,
    "h": 1255,
    "bg": "#e8e8e8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "boxes-empty-room": {
    "w": 1880,
    "h": 1253,
    "bg": "#a8b8b8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "builder-studio-portrait": {
    "w": 1679,
    "h": 1300,
    "bg": "#d8c8b8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "bungalow-lawn": {
    "w": 1880,
    "h": 1255,
    "bg": "#b8a8a8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "carpenter-drilling": {
    "w": 1880,
    "h": 1253,
    "bg": "#080808",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "carpentry-tools-overhead": {
    "w": 1880,
    "h": 1253,
    "bg": "#d8d8d8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "cleaner-portrait": {
    "w": 1880,
    "h": 1253,
    "bg": "#d8d8d8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "cleaning-crew-arriving": {
    "w": 1880,
    "h": 1253,
    "bg": "#181818",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "clearing-leaves": {
    "w": 1880,
    "h": 1253,
    "bg": "#282828",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "commercial-hallway-cart": {
    "w": 1880,
    "h": 1253,
    "bg": "#080808",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "conference-room": {
    "w": 4032,
    "h": 3024,
    "bg": "#e8d8d8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "crew-collaborating-site": {
    "w": 1880,
    "h": 1253,
    "bg": "#b89898",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "crew-ladders-facade": {
    "w": 1880,
    "h": 1253,
    "bg": "#986838",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "crew-painting-interior": {
    "w": 1880,
    "h": 1253,
    "bg": "#c8b8a8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "crew-reviewing-tablet": {
    "w": 1880,
    "h": 1253,
    "bg": "#b8b8a8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "crew-smiling-hardhats": {
    "w": 1880,
    "h": 1253,
    "bg": "#181818",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "crew-talking-outdoor": {
    "w": 1880,
    "h": 1253,
    "bg": "#e8d8c8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "deep-clean-kitchen": {
    "w": 1880,
    "h": 1253,
    "bg": "#e8e8e8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "diverse-crew-discussion": {
    "w": 1880,
    "h": 1253,
    "bg": "#080808",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "engineer-portrait-site": {
    "w": 1880,
    "h": 1253,
    "bg": "#b8b8b8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "exterior-work-lift": {
    "w": 1880,
    "h": 1253,
    "bg": "#181818",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "family-house-facade": {
    "w": 1880,
    "h": 1253,
    "bg": "#a8b8d8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "fixture-light-install": {
    "w": 1880,
    "h": 1255,
    "bg": "#c8c8c8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "grass-trimming": {
    "w": 1880,
    "h": 1253,
    "bg": "#383828",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "handshake-over-documents": {
    "w": 1880,
    "h": 1253,
    "bg": "#080808",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "handshake-senior-client": {
    "w": 1880,
    "h": 1255,
    "bg": "#c8b8b8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "handyman-drill": {
    "w": 1880,
    "h": 1253,
    "bg": "#080808",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "home-with-porch": {
    "w": 1880,
    "h": 1253,
    "bg": "#887858",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "house-yelm-wa": {
    "w": 1880,
    "h": 1253,
    "bg": "#b8c8d8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "interior-open-plan-kitchen": {
    "w": 7680,
    "h": 4320,
    "bg": "#b8b8b8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "interior-refinished-living-room": {
    "w": 7360,
    "h": 4912,
    "bg": "#a8a8a8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "interior-repainted-bedroom": {
    "w": 7008,
    "h": 4672,
    "bg": "#a8a8a8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "interior-sunlit-hardwood": {
    "w": 6000,
    "h": 4000,
    "bg": "#482818",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "labeled-moving-box": {
    "w": 1880,
    "h": 1253,
    "bg": "#989888",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "laser-level-layout": {
    "w": 1880,
    "h": 1253,
    "bg": "#585848",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "leaf-blower-cleanup": {
    "w": 1880,
    "h": 1253,
    "bg": "#080808",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "mopping-interior": {
    "w": 1880,
    "h": 1253,
    "bg": "#b8b8b8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "movers-carrying-boxes": {
    "w": 1880,
    "h": 1253,
    "bg": "#c8c8b8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "mowing-lawn": {
    "w": 1880,
    "h": 1253,
    "bg": "#c8c8b8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "office-desk": {
    "w": 5712,
    "h": 4284,
    "bg": "#d8c8c8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "office-files": {
    "w": 4032,
    "h": 3024,
    "bg": "#483838",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "office-meeting-room": {
    "w": 4032,
    "h": 3024,
    "bg": "#e8d8d8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "organized-drill-bits": {
    "w": 1880,
    "h": 1253,
    "bg": "#987858",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "paint-brush-wall": {
    "w": 1725,
    "h": 1300,
    "bg": "#988878",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "plaster-patching": {
    "w": 1880,
    "h": 1253,
    "bg": "#e8e8e8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "raking-debris": {
    "w": 1880,
    "h": 1253,
    "bg": "#585858",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "restroom-refresh": {
    "w": 5712,
    "h": 4284,
    "bg": "#c8c8c8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "reviewing-blueprints": {
    "w": 1880,
    "h": 1253,
    "bg": "#080808",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "roller-painting": {
    "w": 1880,
    "h": 1253,
    "bg": "#b8b8b8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "roof-replacement-crew": {
    "w": 1880,
    "h": 1253,
    "bg": "#0888d8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "room-under-renovation": {
    "w": 1880,
    "h": 1253,
    "bg": "#483828",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "senior-tradesman-portrait": {
    "w": 1880,
    "h": 1253,
    "bg": "#080808",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "service-van-worker": {
    "w": 1880,
    "h": 1253,
    "bg": "#e8d8c8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "showroom": {
    "w": 5712,
    "h": 4284,
    "bg": "#585858",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "suburban-house-driveway": {
    "w": 1880,
    "h": 1255,
    "bg": "#d8d8e8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "team-discussing-project": {
    "w": 1880,
    "h": 1253,
    "bg": "#181818",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "tools-flatlay": {
    "w": 1880,
    "h": 1253,
    "bg": "#283848",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "toolset-flatlay": {
    "w": 1880,
    "h": 1253,
    "bg": "#080808",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "trailer-exterior": {
    "w": 710,
    "h": 1536,
    "bg": "#080808",
    "widths": [
      400,
      640
    ]
  },
  "trailer-interior": {
    "w": 1536,
    "h": 1152,
    "bg": "#282838",
    "widths": [
      400,
      640,
      900,
      1280
    ]
  },
  "trailer-packout": {
    "w": 1536,
    "h": 1152,
    "bg": "#080818",
    "widths": [
      400,
      640,
      900,
      1280
    ]
  },
  "trailer-secured-load": {
    "w": 1284,
    "h": 1712,
    "bg": "#283848",
    "widths": [
      400,
      640,
      900,
      1280
    ]
  },
  "two-men-confident-portrait": {
    "w": 1880,
    "h": 1254,
    "bg": "#080808",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "van-in-neighborhood": {
    "w": 1880,
    "h": 1253,
    "bg": "#f8f8f8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "walkthrough-tablet": {
    "w": 1880,
    "h": 1253,
    "bg": "#f8f8f8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "wall-sanding": {
    "w": 1880,
    "h": 1253,
    "bg": "#484848",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "washing-exterior-wall": {
    "w": 1880,
    "h": 1253,
    "bg": "#e8e8e8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "work-van-at-house": {
    "w": 1880,
    "h": 1255,
    "bg": "#d8d8d8",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  },
  "worker-spirit-level": {
    "w": 1880,
    "h": 1253,
    "bg": "#989898",
    "widths": [
      400,
      640,
      900,
      1280,
      1600
    ]
  }
} as const satisfies Record<string, ImageMeta>;

export type ImageName = keyof typeof images;
