// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Intrinsic aspect ratio of the brand lockup, so the header and footer can set
// explicit width/height at any rendered height without guessing.
export const logoAspect = 1.7548;

/** Width in px for the lockup rendered at `height` px. */
export const logoWidth = (height: number) => Math.round(height * logoAspect);
