/**
 * One-shot vendoring of the two brand webfonts into public/fonts/.
 *
 * The design system ships `tokens/fonts.css` as an `@import` against
 * fonts.googleapis.com. That costs a DNS + TLS handshake to a third party on the
 * critical path, and the stylesheet it returns blocks first paint. Self-hosting
 * moves the files onto our own origin so they ship over the same connection as
 * the HTML and inherit the immutable cache headers in public/_headers.
 *
 * Run this only when the font set changes; the woff2 files are committed.
 *   node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const OUT = resolve(import.meta.dirname, "..", "public", "fonts");

// Latin only — the site is English, and dropping the other subsets is most of
// the file size. A modern UA string is required or Google returns ttf, not woff2.
const FAMILIES = [
  "Archivo:wght@600;700",
  "IBM+Plex+Sans:wght@400;500;600",
];
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36";

const url =
  "https://fonts.googleapis.com/css2?" +
  FAMILIES.map((f) => `family=${f}`).join("&") +
  "&display=swap";

const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts CSS ${r.status}`);
  return r.text();
});

await mkdir(OUT, { recursive: true });

// Google emits `/* subset */` immediately before each @font-face block, so the
// comment and the block must be matched as a pair — splitting on "@font-face"
// would attach each comment to the preceding block instead.
const PAIR = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;

const faceBlocks = [...css.matchAll(PAIR)].map(([, subset, body]) => ({ subset, body }));
if (faceBlocks.length === 0) throw new Error("Could not parse @font-face blocks from Google CSS");

// Keep latin and latin-ext only; the other subsets are dead weight here.
const wanted = [];
for (const { subset, body } of faceBlocks) {
  if (subset !== "latin" && subset !== "latin-ext") continue;

  const family = /font-family:\s*'([^']+)'/.exec(body)?.[1];
  const weight = /font-weight:\s*(\d+)/.exec(body)?.[1];
  const src = /src:\s*url\((https:[^)]+\.woff2)\)/.exec(body)?.[1];
  if (!family || !weight || !src) continue;

  const slug = family.toLowerCase().replace(/\s+/g, "-");
  const file = `${slug}-${weight}-${subset}.woff2`;
  wanted.push({ family, weight, subset, src, file });
}

// A collision here means two faces resolved to one filename and one would
// silently overwrite the other.
const names = new Set();
for (const f of wanted) {
  if (names.has(f.file)) throw new Error(`Duplicate output filename: ${f.file}`);
  names.add(f.file);
}

if (wanted.length === 0) throw new Error("No latin woff2 faces parsed from Google CSS");

let total = 0;
for (const f of wanted) {
  const buf = Buffer.from(await fetch(f.src).then((r) => r.arrayBuffer()));
  await writeFile(resolve(OUT, f.file), buf);
  total += buf.byteLength;
  console.log(`  ${f.file.padEnd(34)} ${(buf.byteLength / 1024).toFixed(1)} KB`);
}

// Emit the @font-face rules pointing at the local copies. unicode-range is
// preserved per subset so the browser only downloads latin-ext when a page
// actually uses one of its codepoints.
const ranges = {};
for (const { subset, body } of faceBlocks) {
  const range = /unicode-range:\s*([^;]+);/.exec(body)?.[1];
  if (range && !ranges[subset]) ranges[subset] = range.trim();
}

const faces = wanted
  .map((f) =>
    [
      "@font-face{",
      `font-family:'${f.family}';`,
      "font-style:normal;",
      `font-weight:${f.weight};`,
      // swap: show fallback text immediately rather than blocking on the font.
      "font-display:swap;",
      `src:url('/fonts/${f.file}') format('woff2');`,
      ranges[f.subset] ? `unicode-range:${ranges[f.subset]};` : "",
      "}",
    ].join("")
  )
  .join("\n");

const header = [
  "/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.",
  "   Self-hosted replacement for the design system's Google Fonts @import,",
  "   so fonts load from our origin instead of a third party. */",
].join("\n");

await writeFile(
  resolve(import.meta.dirname, "..", "app", "styles", "tokens", "fonts.css"),
  `${header}\n${faces}\n`
);

console.log(`\n${wanted.length} faces, ${(total / 1024).toFixed(1)} KB total`);
