/**
 * Build the responsive image set from source-assets/ into public/img/.
 *
 * The source photos are full-resolution JPEGs — 49 MB across 69 files, one of
 * them 13 MB. Shipping those as-is would dominate page weight, so each one is
 * re-encoded to AVIF + WebP at a ladder of widths and the browser picks the
 * smallest file that covers its layout slot.
 *
 * Output is committed so a Cloudflare Pages build never needs sharp (it is a
 * native dep, and the build image would have to compile it). Re-run locally
 * when source-assets/ changes:
 *   npm run images
 *
 * Also emits app/data/images.generated.ts with intrinsic dimensions, so every
 * <img> can carry width/height and reserve its space before the bytes land —
 * that is what keeps CLS at zero.
 */
import { mkdir, readdir, writeFile, stat } from "node:fs/promises";
import { resolve, parse } from "node:path";
import sharp from "sharp";

const ROOT = resolve(import.meta.dirname, "..");
const SRC = resolve(ROOT, "source-assets", "photos");
const OUT = resolve(ROOT, "public", "img");
const MANIFEST = resolve(ROOT, "app", "data", "images.generated.ts");

// Width ladder. 1600 is the widest rung most of these sources can fill (they are
// ~1880px); 400 covers a half-width card on a phone. Rungs wider than the source
// are skipped rather than upscaled.
const WIDTHS = [400, 640, 900, 1280, 1600];

// Quality falls off as width grows. A 1600px hero is displayed at roughly the
// same physical size as a 900px one on a denser screen, so the per-pixel detail
// budget can drop without a visible difference — and it keeps the LCP image off
// the 200 KB mark. Large hero art also sits under a near-opaque scrim here.
const quality = (w, base, wide) => (w >= 1280 ? wide : base);

// AVIF first (roughly 30% smaller than WebP at equal quality), WebP as the
// fallback for older Safari. No JPEG tier — every browser that can run this
// site supports at least WebP.
const FORMATS = [
  { ext: "avif", encode: (p, w) => p.avif({ quality: quality(w, 52, 40), effort: 6 }) },
  { ext: "webp", encode: (p, w) => p.webp({ quality: quality(w, 74, 66), effort: 6 }) },
];

await mkdir(OUT, { recursive: true });

const files = (await readdir(SRC)).filter((f) => /\.(jpe?g|png)$/i.test(f)).sort();
if (files.length === 0) throw new Error(`No source images found in ${SRC}`);

/** @type {Record<string, {w:number,h:number,bg:string,widths:number[]}>} */
const manifest = {};
let srcBytes = 0;
let outBytes = 0;

for (const file of files) {
  const slug = parse(file).name;
  const srcPath = resolve(SRC, file);
  srcBytes += (await stat(srcPath)).size;

  // `rotate()` with no argument applies the EXIF orientation and strips the tag.
  // Several of these photos are phone shots that render sideways without it.
  const base = sharp(srcPath, { failOn: "error" }).rotate();
  const meta = await base.metadata();
  const srcW = meta.width;
  const srcH = meta.height;
  if (!srcW || !srcH) throw new Error(`Cannot read dimensions for ${file}`);

  // Dominant colour fills the box while the image decodes, instead of a grey
  // flash. Cheaper than a base64 LQIP and costs no extra bytes on the wire.
  const { dominant } = await sharp(srcPath).stats();
  const bg =
    "#" +
    [dominant.r, dominant.g, dominant.b]
      .map((n) => n.toString(16).padStart(2, "0"))
      .join("");

  // Never upscale: drop ladder rungs wider than the source, but always keep at
  // least the smallest so every image has one renderable file.
  const widths = WIDTHS.filter((w) => w <= srcW);
  if (widths.length === 0) widths.push(Math.min(WIDTHS[0], srcW));

  for (const w of widths) {
    const resized = base.clone().resize({ width: w, withoutEnlargement: true });
    for (const { ext, encode } of FORMATS) {
      const outPath = resolve(OUT, `${slug}-${w}.${ext}`);
      const info = await encode(resized.clone(), w).toFile(outPath);
      outBytes += info.size;
    }
  }

  manifest[slug] = { w: srcW, h: srcH, bg, widths };
  process.stdout.write(`  ${slug.padEnd(38)} ${srcW}x${srcH}  ${widths.length} widths\n`);
}

const header = `// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Intrinsic dimensions and encoded widths for every photo in public/img/.
// \`w\`/\`h\` are the source pixel size, used to set the aspect ratio up front so
// images reserve layout space before they load. \`bg\` is the dominant colour,
// painted behind the image while it decodes.

export type ImageMeta = {
  /** Intrinsic width of the source file, in px. */
  w: number;
  /** Intrinsic height of the source file, in px. */
  h: number;
  /** Dominant colour, as a hex string. */
  bg: string;
  /** Widths actually encoded for this image. */
  widths: number[];
};

export const images = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<string, ImageMeta>;

export type ImageName = keyof typeof images;
`;

await writeFile(MANIFEST, header);

// ---------------------------------------------------------------------- logo
//
// The brand lockup is a raster extracted from the supplied print PDF, with an
// opaque white background (so per the design system it may only sit on white or
// #f6f6f6 — never on red or a photo). It is rendered at 46px tall in the header
// and 64px in the footer, so a 360px-wide copy covers both at 2x.
const LOGO_SRC = resolve(ROOT, "source-assets", "logo", "logo-lockup.png");
const logo = sharp(LOGO_SRC);
const logoMeta = await logo.metadata();

// A palette PNG wins here — flat logo art quantises cleanly, and at 128 colours
// it lands at 10 KB versus 35 KB for lossy WebP and 78 KB lossless. So there is
// no WebP tier for the logo; the PNG is both smaller and universally supported.
await logo
  .clone()
  .resize({ width: 360, withoutEnlargement: true })
  .png({ compressionLevel: 9, palette: true, colors: 128, effort: 10 })
  .toFile(resolve(ROOT, "public", "logo-lockup.png"));

const logoAspect = (logoMeta.width ?? 1460) / (logoMeta.height ?? 832);
await writeFile(
  resolve(ROOT, "app", "data", "logo.generated.ts"),
  `// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Intrinsic aspect ratio of the brand lockup, so the header and footer can set
// explicit width/height at any rendered height without guessing.
export const logoAspect = ${logoAspect.toFixed(4)};

/** Width in px for the lockup rendered at \`height\` px. */
export const logoWidth = (height: number) => Math.round(height * logoAspect);
`
);

const mb = (n) => (n / 1024 / 1024).toFixed(1);
console.log(
  `\n${files.length} photos — source ${mb(srcBytes)} MB, encoded ${mb(outBytes)} MB ` +
    `across ${FORMATS.length} formats\n` +
    `Logo: ${logoMeta.width}x${logoMeta.height} → 360px webp + png (aspect ${logoAspect.toFixed(3)})\n` +
    `Manifest: app/data/images.generated.ts`
);
